# Generated by Django 6.0.6 on 2026-07-23 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_alter_mezcal_options_mezcal_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
