# Generated by Django 6.0.6 on 2026-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_alter_mezcal_options_mezcal_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('repartiendo', 'En Reparto'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
