# Generated by Django 6.0.6 on 2026-07-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_orden_estado'),
        ('catalogo', '0004_conversacionia'),
    ]

    operations = [
    ]
