# Generated by Django 6.0.6 on 2026-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_merge_0004_alter_orden_estado_0004_conversacionia'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('recibido', 'Recibido'), ('repartiendo', 'En Reparto'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
